### PR TITLE
Prepare release v0.4.2

### PR DESCRIPTION
**Pull request by tobru**
## Checklist

- [X] Keep pull requests small so they can be easily reviewed.
- [X] Update the documentation.
- [X] Update the ./CHANGELOG.md.

### CODE REVIEW

**Review by srueg — CHANGES_REQUESTED** [review]
Please also update the "unreleased" link:
https://github.com/projectsyn/lieutenant-operator/pull/131/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR104

**Comment by tobru** [comment]
> Please also update the "unreleased" link:
> https://github.com/projectsyn/lieutenant-operator/pull/131/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR104

I would have done this in the last step "After the release is done, switch back the deployment artifacts to point to latest again." in a new PR. WDYT?

**Comment by srueg** [comment]
> After the release is done, switch back the deployment artifacts to point to latest again.

Hmm, we haven't done this so far. It makes the release process even more complicated. I'd propose to skip this.

**Comment by tobru** [comment]
Let's discuss improvements to the release process in https://github.com/projectsyn/documentation/pull/118

**Review by srueg — APPROVED** [review]

**Comment by tobru** [comment]
https://github.com/projectsyn/lieutenant-operator/issues/132 needs to be fixed before we can release this one

**Review by srueg — CHANGES_REQUESTED** [review]
Ah, I see the misunderstanding: I wasn't talking about the `[Unreleased]` title. But about the link here: https://github.com/projectsyn/lieutenant-operator/pull/131/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edL104

It needs to be update to 
```
[Unreleased]: https://github.com/projectsyn/lieutenant-operator/compare/v0.4.2...HEAD
```

**Review by srueg — APPROVED** [review]

**Pull request merged**
